name: Ruby

on:
  push:
    branches:
      - stable
  pull_request:
    branches:
      - stable

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.6' # Specify the Ruby version here

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rspec
